version: '3'

services:
  application:
    build:
      context: ${PROJECT_PATH}/.
      dockerfile: ${PROJECT_PATH}/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["./selenoid","-conf", "/etc/selenoid/browsers.json"]
    ports:
      - "4444:4444"

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "FALSE"
    ports:
      - "5050:5050"
    volumes:
      - ./allure/allure-results:/app/allure-results
      - ./allure/allure-reports:/app/default-reports

  allure_report:
    build:
      context: ${PROJECT_PATH}/allure/.
      dockerfile: ${PROJECT_PATH}/allure/Dockerfile
    ports:
      - 8085:80